/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 * this is a jFrame class named as BMI, which will represent the main UI for the 
 * Application
 * @author AFRAZ
 */
public class BMI extends javax.swing.JFrame {

    /**
     * Creates new form BMI
     */
    public BMI() {
       initComponents();
       /**
        * all fields on jFrame must be started from their initial states as the 
        * form loads
        */
       jTextField5.show(false); 
       jLabel8.show(false);
       setIconImage("Images/BMI.png");
       jTextField1.setFocusable(false);
       jTextField2.setFocusable(false);
       jTextField3.setFocusable(false);
       jTextField4.setFocusable(false);
       jTextField5.setFocusable(false);  
       jLabel25.show(false);
    }
    
    /* this will take input for the Age field on form */
    int age;
    
    /*this will take input for the Height field on form */
    int height;
    
    /*this will take input for the Gender field on form */
    String gender;
    
    /*this will take input for the Weight field on form */
    float weight;

    /**
     * This method is called from
     * within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMI Calculator");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(460, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(520, 520));

        jTextField4.setBackground(new java.awt.Color(204, 102, 0));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 204));
        jTextField4.setText("Enter your Weight");
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField4MouseEntered(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(204, 102, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 204));
        jTextField1.setText("Enter your Age");
        jTextField1.setCaretColor(new java.awt.Color(51, 51, 51));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(204, 102, 0));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 204));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField5MouseEntered(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("ft");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Gender:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("inches");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("inch");

        jComboBox3.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Lb" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("kg");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MCs\\Documents\\NetBeansProjects\\Lab4\\src\\lab4\\Images\\switch.png")); // NOI18N
        jButton2.setText("Switch to 'inches'");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Age:");

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose Gender", "Male", "FeMALE" }));

        jTextField3.setBackground(new java.awt.Color(204, 102, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 204));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField3MouseEntered(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Weight:");

        jTextField2.setBackground(new java.awt.Color(204, 102, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 204));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Height:");

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("BMI");

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Fat %age");

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Ideal Weight");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 204));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/Images/if_73-Calculator_2123899.png"))); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("BMI Classification:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/Images/player-09-24.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 0));
        jLabel18.setText("Normal                      (18.6 - 24.99)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 0));
        jLabel17.setText("Underweigt                (17 - 18.5) ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("Severly underweight  (< 17)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 0));
        jLabel19.setText("Overweight               (25 - 29.99)");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("Obese                        (30 - 35)");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText("Severly Obese            (> 35)");

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel24.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/Images/oie_291553461hSsQ584.png"))); // NOI18N
        jLabel24.setText("BMI Calculator");

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Kg");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel22))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel21))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))))))
                .addGap(64, 64, 64))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(97, 97, 97)
                .addComponent(jLabel22)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * when the Calculate button is pressed on form , then this method will be
     * invoked
     * @param evt
     * this is default action event
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /**
         * First of method will check if all the fields on form are 
         * filled-out correctly. 
         * ERROR will arise for any discrepancy 
         */
        
        /* check for Age field */
        if (jTextField1.getText().equals("Enter your Age") 
                || jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "pl, enter your Age", "Error", 0);
            return;
        }
        
        /* check for Height field if "feet+inches" option is seleccted */
        if (jTextField2.isShowing() && jTextField3.isShowing()) { 
            if (jTextField2.getText().equals("") 
                    || jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, 
                        "pl, enter your Height correctly", "Error", 0);
                return;
            }   
        } 
        
        /* check for Height field if only inches option is selected */
        else if (jTextField5.isShowing()) {         
            if (jTextField5.getText().equals("")) {
                JOptionPane.showMessageDialog(null,
                        "pl, enter your Height correctly", "Error", 0);
                return;
            }
        }
        
        /* check for Gender field */
        if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "pl, Select your Gender", "Error"
                    , 0);
            return;
        } 
        
        /* check for Weight field */
        else if (jTextField4.getText().equals("Enter your Weight")
                || jTextField4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "pl, enter your Weight", "Error"
                    , 0);
            return;
        }
        
        /**
         * following methods are called to set their respective labels on form
         * to show their values
         */
        jLabel10.setText(getBMI());     // method to set BMI label
        jLabel11.setText(getIBW());     // method to set Ideal Weight label
        jLabel14.setText(getBF());      // method to set Body Fat label 
        
        /* variable will contain value given by getBMI() method */
        float bmi = Float.parseFloat(getBMI());
        
        /* variable will contain value given by getIBW() method */
        float ibw = Float.parseFloat(getIBW());
        
        /* variable will contain value given by getBF() method */
        float bf = Float.parseFloat(getBF());
        
        /* this is the font to highlight the respective label in 
         * BMI Classification chart according to the  calculated BMI value.
         */
        Font f = jLabel22.getFont();
        
        /**
         * in each case below the the respected label highlighted in BMI 
         * classification chart according to the BMI value generated by 
         * Application will take the above font & also usual BMI Labels 
         * on form will take the color of that highlighted label in chart.
         * & In each case a special Comment with a specific color according to 
         * the BMI generated will be shown on form. 
         */
        if (bmi < 17) {
            jLabel23.setFont(Font.getFont("Size", f));    // chart label
            jLabel17.setFont(Font.getFont("Size", f));    // chart label
            jLabel18.setFont(Font.getFont("Size", f));    // chart label
            jLabel19.setFont(Font.getFont("Size", f));    // chart label
            jLabel20.setFont(Font.getFont("Size", f));    // chart label
            jLabel10.setForeground(Color.red );           // usual BMI label
            jLabel15.setForeground(Color.red);            // usual BMI label
            jLabel15.setText("Time to Grab a bite...Sever");  // special comment
           
            /* highlighted label in BMI Classification Chart */
            jLabel16.setFont(Font.getFont("Size", jLabel21.getFont()));
        } else if (bmi < 18.50 && bmi >=17) {
            jLabel23.setFont(Font.getFont("Size", f));  // chart lable
            jLabel16.setFont(Font.getFont("Size", f));  // chart lable
            jLabel18.setFont(Font.getFont("Size", f));  // chart lable
            jLabel19.setFont(Font.getFont("Size", f));  // chart lable
            jLabel20.setFont(Font.getFont("Size", f));  // chart lable
            jLabel10.setForeground(Color.orange );      // usual label
            jLabel15.setForeground(Color.orange);       // usual label
            
            /* highlighted label in BMI Classification Chart */
            jLabel17.setFont(Font.getFont("Size", jLabel21.getFont()));
            jLabel15.setText("Time to Grab a bite..."); // special comment
        } else if (bmi > 18.50 && bmi < 24.99) {
            jLabel23.setFont(Font.getFont("Size", f));  // chart lable
            jLabel17.setFont(Font.getFont("Size", f));  // chart lable
            jLabel16.setFont(Font.getFont("Size", f));  // chart lable
            jLabel19.setFont(Font.getFont("Size", f));  // chart lable
            jLabel20.setFont(Font.getFont("Size", f));  // chart lable
            jLabel10.setForeground(Color.GREEN);        // usual lable
            jLabel15.setForeground(Color.GREEN);        // usual lable
            jLabel15.setText("Great shape...");         // special label
            
            /* highlighted label in BMI Classification Chart */
            jLabel18.setFont(Font.getFont("Size", jLabel21.getFont()));
        } else if (bmi > 24.99 && bmi <29.99) {
            jLabel23.setFont(Font.getFont("Size", f));  // chart lable
            jLabel17.setFont(Font.getFont("Size", f));  // chart lable
            jLabel18.setFont(Font.getFont("Size", f));  // chart lable
            jLabel16.setFont(Font.getFont("Size", f));  // chart lable
            jLabel20.setFont(Font.getFont("Size", f));  // chart lable
            jLabel10.setForeground(Color.orange);       // usual lable
            jLabel15.setForeground(Color.orange);       // usual lable
            jLabel15.setText("Time for a run...");      // special comment
            
            /* highlighted label in BMI Classification Chart */
            jLabel19.setFont(Font.getFont("Size", jLabel21.getFont()));
        } else if (bmi > 29.99) {
            jLabel23.setFont(Font.getFont("Size", f));  // chart lable
            jLabel17.setFont(Font.getFont("Size", f));  // chart lable
            jLabel18.setFont(Font.getFont("Size", f));  // chart lable
            jLabel19.setFont(Font.getFont("Size", f));  // chart lable
            jLabel16.setFont(Font.getFont("Size", f));  // chart lable
            jLabel10.setForeground(Color.red );         // usual lable
            jLabel15.setForeground(Color.red);          // usual lable
            jLabel15.setText("Time for a run...");      // special comment
            
            /* highlighted label in BMI Classification Chart */
            jLabel20.setFont(Font.getFont("Size", jLabel21.getFont()));
        }
        if (bmi > 35) {
            jLabel17.setFont(Font.getFont("Size", f));  // chart lable
            jLabel18.setFont(Font.getFont("Size", f));  // chart lable
            jLabel19.setFont(Font.getFont("Size", f));  // chart lable
            jLabel16.setFont(Font.getFont("Size", f));  // chart lable
            jLabel20.setFont(Font.getFont("Size", f));  // chart lable
            
            /* highlighted label in BMI Classification Chart */
            jLabel23.setFont(Font.getFont("Size", jLabel21.getFont()));
        }
        
        /* this statment will check if gender selected is Male */
        if (jComboBox1.getSelectedIndex() == 1) {
            
            /**
             * in each case below the color of the Fat %age label will be set 
             * according to the Fat value generated by getBF() method
             */
            if (bf >= 2 && bf <= 13) {
                jLabel14.setForeground(Color.orange);   // Fat label
            } else if (bf > 13 &&  bf <= 17) {
                jLabel14.setForeground(Color.GREEN);    // Fat label
            } else if (bf >17 && bf <=25) {
                jLabel14.setForeground(Color.orange);   // Fat label
            } else if (bf > 25) {
                jLabel14.setForeground(Color.red);      // Fat label
            }
        }
        
        /* this statment will check if gender selected is FeMale */
        else if (jComboBox1.getSelectedIndex() == 2) {
            if (bf >= 10 && bf <= 20) {
                jLabel14.setForeground(Color.orange);   // Fat label
            } else if (bf > 20 &&  bf <= 24) {
                jLabel14.setForeground(Color.GREEN);    // Fat label
            } else if (bf >24 && bf <=31) {
                jLabel14.setForeground(Color.orange);   // Fat label
            } else if (bf > 31) {
                jLabel14.setForeground(Color.red);      // Fat label
            }
        }
        
        /* setting the color of ideal body weight color */
        jLabel11.setForeground(Color.green);
        
        /**
         * following check will set the weight label aside the weight field on 
         * form to be set according to the value selected from the comboxBox 
         * for weight property. 
         */
        
        /* check for Kg option  */
        if (jComboBox3.getSelectedIndex() == 0) {
            jLabel25.setText("Kg");
            jLabel25.show(true);
        } else {                      // check for Lb option
            jLabel25.setText("Lb");
            jLabel25.setText("Lb");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
     
    /**
     * this method will be invoked, when user will press the button on form to
     * change the height format option
     * @param evt
     * default action argument
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        /* check for the selected Height format if it is only inches selected */
        if (jButton2.getText().equals("Switch to \'inches\'")) {
            /**
             * field for only inches format option will become visible 
             */
            jTextField5.show(true);
            jLabel8.show(true);
            jTextField2.show(false);
            jLabel5.show(false);
            jTextField3.show(false);
            jLabel6.show(false);
            jButton2.setText("Switch to \'Feets+Inches\'");

        } else {
            /* field for "feet+inches" format option will become visible */
            jTextField5.show(false);
            jLabel8.show(false);
            jTextField2.show(true);
            jLabel5.show(true);
            jTextField3.show(true);
            jLabel6.show(true);
            jButton2.setText("Switch to \'inches\'");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /* event when mouse entterd the Age Textfield on form */
    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        if(jTextField1.getText().equals("")) {
            jTextField1.setText("Enter your Age");
        }
        if (jTextField4.getText().equals("")) {
            jTextField4.setText("Enter your Weight");
        }
        jTextField3.setFocusable(false);
        jTextField4.setFocusable(false);
        jTextField5.setFocusable(false);
        jTextField1.setFocusable(false);        
    }//GEN-LAST:event_jTextField2MouseClicked

    /* event to set weight format label aside the weight textfield */
    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        jLabel7.setText(jComboBox3.getItemAt(jComboBox3.getSelectedIndex()));
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    /* event for mouse entering for only inches format with height*/
    private void jTextField4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseEntered
        jTextField4.setFocusable(true);
    }//GEN-LAST:event_jTextField4MouseEntered

    /* event when mouse clicked in inches field for ft+in option with height*/
    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        if(jTextField1.getText().equals("")) {
            jTextField1.setText("Enter your Age");
        }
        if (jTextField4.getText().equals("")) {
            jTextField4.setText("Enter your Weight");
        }
    }//GEN-LAST:event_jTextField3MouseClicked

    /* event for key pressed in Age field*/
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(jTextField1.getText().equals("")) {
                jTextField1.setText("Enter your Age");
            }
            jTextField1.setFocusable(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /* event for mouse clicked in only inches filed with Height*/
    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        if(jTextField1.getText().equals("")) {
        jTextField1.setText("Enter your Age");
    }
        if(jTextField4.getText().equals("")) {
            jTextField4.setText("Enter your Weight");
        }
    
        jTextField4.setFocusable(false);
        jTextField2.setFocusable(false);
        jTextField3.setFocusable(false);
        jTextField1.setFocusable(false);
    }//GEN-LAST:event_jTextField5MouseClicked

    /* event when mouse is pressed in Age field */
    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        jTextField2.setFocusable(false);
        jTextField3.setFocusable(false);
        jTextField5.setFocusable(false);
        jTextField1.setFocusable(true);
        if (jTextField4.getText().equals("")) {
            jTextField4.setText("Enter your Weight");
        }
        if (jTextField1.getText().equals("Enter your Age")) {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1MousePressed

    /* event for mouse entered in Age field */
    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        jTextField1.setFocusable(true);
    }//GEN-LAST:event_jTextField1MouseEntered

    /* event for mouse entered in feet field for ft+in option with Height*/
    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        jTextField2.setFocusable(true);
    }//GEN-LAST:event_jTextField2MouseEntered

    /* event for mouse entered in weight field */
    private void jTextField5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseEntered
        jTextField5.setFocusable(true);
    }//GEN-LAST:event_jTextField5MouseEntered

    /* event for mouse entered in inch field for ft+in option with height */
    private void jTextField3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseEntered
        jTextField3.setFocusable(true);
    }//GEN-LAST:event_jTextField3MouseEntered

    /* event when key is pressed in weight field */
    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField5.setFocusable(false);
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    /* event when key is pressed in feet field for ft+in option with height */
    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField2.setFocusable(false);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    /* event when key is pressed in inch field for ft+in option with height */
    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField3.setFocusable(false);
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    /* event when key is pressed in only inches field with height */
    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextField4.getText().equals("")) {
                jTextField4.setText("Enter your Weight");
            }
            jTextField4.setFocusable(false);
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    /* event when mouse is clicked in only inches field with height */
    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setFocusable(true);
        jTextField1.setFocusable(false);
        jTextField5.setFocusable(false);
        jTextField3.setFocusable(false);
        jTextField2.setFocusable(false);
        if (jTextField1.getText().equals("")) {
            jTextField1.setText("Enter your Age");
        }
        
        if (jTextField4.getText().equals("Enter your Weight")) {
            jTextField4.setText("");
        }
    }//GEN-LAST:event_jTextField4MouseClicked

    /**
     * this method will be called when Reset button will be pressed on form &
     * it will reset all the fields to their initial states
     * @param evt 
     * default action event
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("Enter your Age");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("Enter your Weight");
        jTextField5.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jLabel25.show(false);
        
        Font f= jLabel22.getFont();
        
        jLabel9.setForeground(Color.lightGray);
        jLabel12.setForeground(Color.lightGray);
        jLabel13.setForeground(Color.lightGray);
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel14.setText("");
        jLabel15.setText("");
        jLabel16.setFont(Font.getFont("Size", f));
        jLabel17.setFont(Font.getFont("Size", f));
        jLabel18.setFont(Font.getFont("Size", f));
        jLabel19.setFont(Font.getFont("Size", f));
        jLabel20.setFont(Font.getFont("Size", f));
        jLabel23.setFont(Font.getFont("Size", f));
    }//GEN-LAST:event_jButton3ActionPerformed

    /* this method will be called when Exit button will be pressed */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private void initializecomponent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * this method will return the BMI value calculated from input values
     * @return 
     * a String value for the calculated float BMI value.
     */
    public String getBMI(){
        
        /* setting all attributes to the secified values from fields on form */
        age = Integer.parseInt(jTextField1.getText());
        height = 0;
        gender = jComboBox1.getSelectedItem().toString();
        weight = Float.parseFloat(jTextField4.getText());
   
        /** 
         * checking option selected for height format  & then 
         * setting height according to that option.
         */
        if (jTextField5.isShowing() && jLabel8.isShowing()) {
          height= Integer.parseInt(jTextField5.getText());
        } else if (jTextField2.isShowing() && jLabel5.isShowing()
                && jTextField3.isShowing() && jLabel6.isShowing()) {
            int feet= Integer.parseInt(jTextField2.getText());
            int inches= Integer.parseInt(jTextField3.getText());
            height = (feet * 12) + inches;
        }
        
        /* temporary variable to get BMI value */
        float BMI = 0;
        
        /**
         * First checking for Wight Format & then setting the  BMI value to 
         * the earlier initialized variable.
         */
        if (jComboBox3.getSelectedIndex() == 1) {
            float constant=(float) .025;
            float height2 = height * constant;
            weight = (float) (weight * .45);
            
            BMI = (float)(weight / (height2 * height2));
        } else if (jComboBox3.getSelectedIndex() == 0) {
            float constant=(float) .025;
            float height2 = height * constant;
            weight = (float) (weight * .45);
            weight = (float)(weight * 2.204623);
            BMI = (float)(weight / (height2 * height2)); 
        }
        
        /**
         * converting BMI float variable value to String to set the respective
         * labels  on the form.
         */
        String BMI2=Float.toString(BMI);
        return BMI2;
    }
    
    /**
     * this method will return the Ideal Weight value calculated from input values
     * @return 
     * a String value for the calculated float Ideal Weight value.
     */
    public String getIBW() {
        
        /* setting all attributes to the secified values from fields on form */
        age = Integer.parseInt(jTextField1.getText());
        weight = Float.parseFloat(jTextField4.getText());
        gender = jComboBox1.getSelectedItem().toString();
        height = 0;
        
        /** 
         * checking option selected for height format  & then 
         * setting height according to that option.
         */
        if (jTextField5.isShowing() && jLabel8.isShowing()) {
          height= Integer.parseInt(jTextField5.getText());
        } else if (jTextField2.isShowing() && jLabel5.isShowing()
                && jTextField3.isShowing() && jLabel6.isShowing()) {
            int feet= Integer.parseInt(jTextField2.getText());
            int inches= Integer.parseInt(jTextField3.getText());
            height = (feet * 12) + inches;
        }
        
        float height2 = (float) (height * 2.54);  // converting height to cm's
        float IBW = 0;
        
        /* calculating ideal weight according to the gender selected */
        if (jComboBox1.getSelectedIndex() == 1) {
           IBW = (height2 - 100) - ((height2 - 100) * (float) 0.1);
       } else  if (jComboBox1.getSelectedIndex() == 2) {
           IBW = (height2 - 100) - ((height2 - 100) * (float) 0.15);
       }
        
        /**
         * temporary String variable to hold ideal weight value for setting 
         * respective Ideal Weight Label on form
         */
        String IBW2 = "";
        
      /* checking the weight format then converting weight to selected format */
       if (jLabel7.getText().equals("Kg") || jLabel7.getText().equals("kg")) {
           IBW2 = Float.toString(IBW);
       } else if(jLabel7.getText().equals("Lb")) {
           IBW = (float)(IBW * 2.204623);
           IBW2 = Float.toString(IBW);
       }
       return IBW2;
    }
    
    /**
     * this method will return the Body Fat value calculated from input values
     * @return 
     * a String value for the calculated float Body Fat value.
     */
    public String getBF() {
        
        /* setting all attributes to the secified values from fields on form */
        age = Integer.parseInt(jTextField1.getText());
        weight = Float.parseFloat(jTextField4.getText());
        gender = jComboBox1.getSelectedItem().toString();
        height = 0;
        
        /** 
         * checking option selected for height format  & then 
         * setting height according to that option.
         */
        if (jTextField5.isShowing() && jLabel8.isShowing()) {
          height= Integer.parseInt(jTextField5.getText());
        } else if (jTextField2.isShowing() && jLabel5.isShowing()
                && jTextField3.isShowing() && jLabel6.isShowing()) {
            int feet= Integer.parseInt(jTextField2.getText());
            int inches= Integer.parseInt(jTextField3.getText());
            height = (feet * 12) + inches;
        }
        
        /* temporary variable to hold the float Body Fat value */
        float BF = 0;
        
        /* calculating BF value according to the gender selected */
        if(jComboBox1.getSelectedIndex() == 1) {
            BF = (float)(1.20 * Float.parseFloat(getBMI()) + (0.23 * age)
                    - (3.6 * 1) - 16.2);
        } else if (jComboBox1.getSelectedIndex() == 2) {
            BF = (float)(1.20 * Float.parseFloat(getBMI()) + (0.23 * age)
                    - (3.6 * 0) - 5.4);
        }
        
        /**
         * converting BMI float variable value to String to set the respective
         * labels  on the form.
         */
        String BF2 = Float.toString(BF);
        return BF2;
    }

    /* setting the icon of the Form to the given image path */
    private void setIconImage(String path) {
       this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass()
               .getResource(path) ));
    }
     
}
